name: DigitalTwin Lap2010_2_Transportwagen

on:
  push:
    branches: [ main ]

env:
      PROJECT_PATH: PlcDigitalTwinAutoTest/DtLap2010_2_Transportwagen/DtLap2010_2_Transportwagen.csproj
      
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'LibPlcKommunikation/IpAdressenSiemens.json'
      env:
        Adress: "192.168.0.10"
    
    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o PublishMin
    
    - uses: actions/upload-artifact@v2
      with:
        name: DtLap2010_2_Transportwagen Min
        path: PublishMin
